server:
  port: 8084
  session:
    timeout: 1800
  tomcat: 
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60
 
spring:
   datasource: 
     name: master
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/app_center_db
     username: root
     password: liliu 
   redis:
     host: 127.0.0.1
     password: liliu
     port: 6379 
     database: 1
     timeout: 3000
     pool: 
       min-idle: 100
       max-idle: 300
       max-active: 800 
myPugin: 
  session: 
    myDomainName: null
  projectName: AppCenter
  location: c://config/thirdParty.properties
  requestAuth: requestAuthDev
  sevenSecondsDomainUrl: http://192.168.7.111
  rabbitmq: 
    APPWEBREAD_DIRECT_EXCHANGE: test.appwebread.activitycenter.exchange.direct
    APPWEBREAD_DIRECT_ROUTINGKEY: test.appwebread.activitycenter.routingkey.direct
    APPWEBREAD_DIRECT_QUEUE: test.appwebread.activitycenter.queue.direct
